;;;-*-Mode:LISP; Syntax: Common-Lisp;Package:(gina (GINA lisp));-*-

;; !!! Do not edit !!!
;; This code was generated by the GINA Interface Builder.

(in-package 'gina)
(use-package '(gina lisp))

(defclass finder-shell (document-shell)
          ((form :accessor form) (parent-button :accessor parent-button)
           (directory-label :accessor directory-label)
           (file-list :accessor file-list) (button-row :accessor button-row)
           (start-button :accessor start-button)
           (refresh-button :accessor refresh-button))
          (:documentation ""))

(defun make-finder-shell (document &aux box)
  (setq box
        (make-document-shell document :class 'finder-shell :width 244 :height
                             320))
  (setf (form box) (make-form box))
  (setf (parent-button box) (make-push-button (form box) "Parent Directory"))
  (setf (directory-label box) (make-label (form box) "/home/spenke"))
  (setf (file-list box)
        (make-scrollable-selection-list (form box) '("file1" "file2" "file3")))
  (setf (button-row box)
        (make-row-column (form box) :orientation :horizontal :spacing 50))
  (setf (start-button box) (make-push-button (button-row box) " Open "))
  (setf (refresh-button box) (make-push-button (button-row box) " Refresh "))
  (define-form-constraint (parent-button box) :top-attachment :form :top-offset
                          10 :left-attachment :form :left-offset 10
                          :right-attachment :none :bottom-attachment :none)
  (define-form-constraint (directory-label box) :top-attachment :widget
                          :top-widget (parent-button box) :top-offset 10
                          :left-attachment :form :left-offset 10
                          :right-attachment :none :bottom-attachment :none)
  (define-form-constraint (file-list box) :top-attachment :widget :top-widget
                          (directory-label box) :top-offset 10 :left-attachment
                          :form :left-offset 10 :right-attachment :form
                          :right-offset 10 :bottom-attachment :widget
                          :bottom-widget (button-row box) :bottom-offset 10)
  (define-form-constraint (button-row box) :top-attachment :none
                          :left-attachment :form :left-offset 10
                          :right-attachment :none :bottom-attachment :form
                          :bottom-offset 9)
  box)
