;;; -*- Mode: LISP; Syntax: Common-lisp; Base: 10; Package: USER;-*-

(gina:defginapackage :hello)
(gina:defginapackage :tetris)
(gina:defginapackage :mandel)
(gina:defginapackage :hyper)
(gina:defginapackage :dd)
(gina:defginapackage :chess)
(gina:defginapackage :bitedit)
(gina:defginapackage :pac)
(gina:defginapackage :txedit)
(gina:defginapackage :output)
(gina:defginapackage :lisp-widgets)
(gina:defginapackage :gredit)
(gina:defginapackage :clock)
(gina:defginapackage :micky)
(gina:defginapackage :ss)
(gina:defginapackage :calc)
